In [1]:
import pandas as pd
import numpy as np

In [2]:
# Exemplo para juntar os clientes das duas pastas
#df_train = pd.read_csv('train/df_Products.csv')
#df_test = pd.read_csv('test/df_Products.csv')

# Concatena (empilha) os dois arquivos em um único DataFrame
#df = pd.concat([df_train, df_test], ignore_index=True)
# Salva o DataFrame unificado em um novo arquivo no seu disco
#df.to_csv('df_Products.csv', index=False)

### 1. Limpeza de Clientes

In [3]:
# carregando dataset de clientes
df_Customers =pd.read_csv('df_Customers.csv' )

In [4]:
# Visuzalização do dataset
df_Customers.head(20)

     customer_id  customer_zip_code_prefix       customer_city customer_state
0   hCT0x9JiGXBQ                     58125     Varzea Paulista             SP
1   PxA7fv9spyhx                      3112  Armacao Dos Buzios             RJ
2   g3nXeJkGI0Qw                      4119             Jandira             SP
3   EOEsCQ6QlpIg                     18212          Uberlandia             MG
4   mVz5LO2Vd6cL                     88868            Ilhabela             SP
5   UkqnhxmX7YMP                     25902         Porto Uniao             SC
6   85jiDiGSfhTu                      4762           Guarulhos             SP
7   gDdkaN8b9s1g                     75870          Mogi-Guacu             SP
8   9Csx6oXlpLl1                     69068           Bebedouro             SP
9   gZTPKLPRnreg                     20921           Sao Paulo             SP
10  TDEBQrhIwApB                      1223           Itaperuna             RJ
11  1k71TCYNFCzj                     11703               Serra             ES
12  IfWKDQHkjLDd                     32407         Sao Goncalo             RJ
13  kZ0rkJCJ6N5y                     13843     Mogi Das Cruzes             SP
14  zsCKIdqYLV01                      2961               Caico             RN
15  FrEvnEiMKGpr                     28630           Sao Paulo             SP
16  3zvaY9gUH9bO                     59020         Barra Mansa             RJ
17  bUornDCZmRD4                      3440           Sao Paulo             SP
18  qEVfsXFU3er9                      3936               Apora             BA
19  mPg90mQwmDOP                     85140            Brasilia             DF

In [5]:
# identificando os tipos de dados
df_Customers.dtypes

customer_id                   str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [6]:
# verificando se tem arquivos nulos
df_Customers.isnull().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [7]:
# # Retorna o resumo estatístico das colunas numéricas (contagem, média, desvio padrão, min e max)
df_Customers. describe()

       customer_zip_code_prefix
count             127595.000000
mean               40483.681610
std                31173.651747
min                 1003.000000
25%                 9785.000000
50%                35440.000000
75%                69906.000000
max                99990.000000

In [8]:
# Retorna a quantidade total de linhas totalmente duplicadas
total_duplicados_Customers = df_Customers.duplicated().sum()
total_duplicados_Customers

np.int64(0)

In [9]:
# Convertendo letra inicial de cada palavra em Maiúscula
df_Customers['customer_city']=df_Customers['customer_city'].str.title()

# Visuzlizar a coluna para conferir
print(df_Customers['customer_city'].head())

0       Varzea Paulista
1    Armacao Dos Buzios
2               Jandira
3            Uberlandia
4              Ilhabela
Name: customer_city, dtype: str

In [10]:
# convertendo colunas para o tipo string

df_Customers['customer_id'] = df_Customers['customer_id'].astype(str)

df_Customers['customer_state'] = df_Customers['customer_state'].astype(str)

df_Customers['customer_city'] = df_Customers['customer_city'].astype(str)

In [11]:
# Verificando se tem espaços vazios nas colunas
tem_espacos = (df_Customers['customer_state'] != df_Customers['customer_state'].str.strip()).any()
tem_espacosII = (df_Customers['customer_id'] != df_Customers['customer_id'].str.strip()).any()
tem_espacosIII = (df_Customers['customer_city'] != df_Customers['customer_city'].str.strip()).any()

In [12]:
# mostra a quantidade de linhas com espaços vazios
for col in df_Customers.select_dtypes('object').columns:
    tem_espacos = (df_Customers[col] != df_Customers[col].str.strip()).sum()
    print(f"{col}: {tem_espacos}")

customer_id: 0
customer_city: 0
customer_state: 0

C:\Users\campo\AppData\Local\Temp\ipykernel_19336\3891550723.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_Customers.select_dtypes('object').columns:

### 2. Limpeza Intens do Pedido

In [13]:
# Mantenha o padrão padronizado (sem o "s" extra no Order)
df_OrderItems = pd.read_csv('df_OrderItems.csv')

In [14]:
# Visuzalização do dataset
df_OrderItems.head(10)

       order_id    product_id     seller_id    price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF   223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs   170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD    64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf   264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr   779.90             30.66
5  VjTVGzqe8U6R  TpFZIk33uyGn  XePbD5Ocm6Yk   263.90             40.26
6  xNba906m4TM1  Y0T4Ca4BXK8U  ftbUjJ6Gsazg   966.90             98.76
7  VEDSMTavbQwk  IUykT5z5LcPW  RKad98cTxhSb  1534.90             66.90
8  DzNM8wrcMGFH  0UHKKyYmxWfq  K0qPVGdA91KO   779.00             34.86
9  NpJz7zF9U1ae  MJ82dNJNiV7U  2a07LobkzHUx    95.03             60.35

In [15]:
df_OrderItems.dtypes

order_id                str
product_id              str
seller_id               str
price               float64
shipping_charges    float64
dtype: object

In [16]:
df_OrderItems.isnull().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [17]:
df_OrderItems.describe()

               price  shipping_charges
count  127595.000000     127595.000000
mean      341.380366         44.256468
std       558.307510         37.692326
min         0.850000          0.000000
25%        59.650000         20.020000
50%       136.900000         34.870000
75%       399.200000         57.160000
max      6735.000000        409.680000

In [18]:
total_duplicados_OrderItem = df_OrderItems.duplicated().sum()
total_duplicados_OrderItem

np.int64(0)

In [19]:
# convertendo colunas para o tipo string

df_OrderItems['order_id'] = df_OrderItems['order_id'].astype(str)
df_OrderItems['product_id'] = df_OrderItems['product_id'].astype(str)
df_OrderItems['seller_id'] = df_OrderItems['seller_id'].astype(str)

In [20]:
# mostra a quantidade de linhas com espaços vazios
for col in df_OrderItems.select_dtypes('object').columns:
    tem_espacos = (df_OrderItems[col] != df_OrderItems[col].str.strip()).sum()
    print(f"{col}: {tem_espacos}")

order_id: 0
product_id: 0
seller_id: 0

C:\Users\campo\AppData\Local\Temp\ipykernel_19336\2027120223.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_OrderItems.select_dtypes('object').columns:

### 3. Limpeza Pedido

In [21]:
# Carregando dataset
df_Orders  =pd.read_csv('df_Orders.csv')
df_Orders.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18
5,VjTVGzqe8U6R,UkqnhxmX7YMP,delivered,2017-09-01 14:38:16,2017-09-01 14:50:24,2017-09-15 18:57:50,2017-09-26
6,xNba906m4TM1,85jiDiGSfhTu,delivered,2018-04-23 21:03:00,2018-04-24 18:18:18,2018-04-25 20:14:38,2018-05-04
7,VEDSMTavbQwk,gDdkaN8b9s1g,delivered,2018-02-23 14:49:39,2018-02-23 15:16:13,2018-04-02 14:12:50,2018-03-15
8,DzNM8wrcMGFH,9Csx6oXlpLl1,delivered,2017-11-24 19:12:37,2017-11-25 04:54:03,2017-12-11 13:09:32,2017-12-14
9,NpJz7zF9U1ae,gZTPKLPRnreg,delivered,2017-11-30 11:48:21,2017-11-30 13:31:19,2017-12-14 16:38:47,2018-01-03

In [22]:
# Verificando quantas linhas tem
df_Orders.shape

(127595, 7)

In [23]:
# Verificando tipos
df_Orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_timestamp        str
order_estimated_delivery_date    str
dtype: object

In [24]:
# Convertendo colunas que não estão em datatime para data time
df_Orders['order_purchase_timestamp'] = pd.to_datetime(df_Orders['order_purchase_timestamp'])
df_Orders['order_approved_at'] = pd.to_datetime(df_Orders['order_approved_at'])
df_Orders['order_delivered_timestamp'] = pd.to_datetime(df_Orders['order_delivered_timestamp'])
df_Orders['order_estimated_delivery_date'] = pd.to_datetime(df_Orders['order_estimated_delivery_date'])

In [25]:
# Quantos dados NAN existem
df_Orders.isnull().sum()

order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                   16
order_delivered_timestamp        40168
order_estimated_delivery_date    38279
dtype: int64

In [26]:
# mostrando dados nulos
df_Orders[df_Orders["order_estimated_delivery_date"].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
89316,u6rPMRAYIGig,I74lXDOfoqsp,não informado,2017-11-18 12:29:57,2017-11-18 12:46:08,NaT,NaT
89317,ohY8f4FEbX19,47TuLHF2s7X5,não informado,2018-06-02 17:13:12,2018-06-02 20:12:23,NaT,NaT
89318,I28liQek73i2,dQ0dqI8Qwlj8,não informado,2018-01-08 11:01:30,2018-01-09 07:24:03,NaT,NaT
89319,bBG1T89mlY8W,iQCmWhNkIczb,não informado,2017-03-10 10:24:46,2017-03-10 10:24:46,NaT,NaT
89320,CYxJJSQS8Lbo,Dp2g6JH8tO5Z,não informado,2017-12-02 10:04:07,2017-12-05 04:13:30,NaT,NaT
...,...,...,...,...,...,...,...
127590,QKBW3XKevmfn,Dw3aCTFf4Q4G,não informado,2018-08-24 11:54:56,2018-08-24 12:05:22,NaT,NaT
127591,Tjiw9bj8HtLr,JmHJqJvpVcJs,não informado,2017-03-25 20:39:11,2017-03-25 20:50:17,NaT,NaT
127592,mCPofb7A1aTq,ro5DikwWCC3j,não informado,2018-08-16 13:39:30,2018-08-17 03:31:06,NaT,NaT
127593,scVuqN10zbgb,R25nE2rl77AU,não informado,2018-06-27 13:17:05,2018-06-28 08:50:58,NaT,NaT
127594,oLKXX8tqU6eQ,oOvkrmF7ZZbI,não informado,2017-09-08 09:22:24,2017-09-08 09:35:20,NaT,NaT

In [27]:
# Tratamento das colunas que tem dados NAN
df_Orders['order_status'] = df_Orders['order_status'].fillna('não informado')
df_Orders['order_approved_at'] = df_Orders['order_approved_at'].fillna('NaN')
df_Orders['order_estimated_delivery_date'] = df_Orders['order_estimated_delivery_date'].fillna('NaN')
df_Orders['order_delivered_timestamp'] = df_Orders['order_delivered_timestamp'].fillna('NaN')

In [28]:
# Verificação final
print(df_Orders.info())
print("\nContagem final de nulos:")
print(df_Orders.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 127595 entries, 0 to 127594
Data columns (total 7 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       127595 non-null  str
 1   customer_id                    127595 non-null  str
 2   order_status                   127595 non-null  str
 3   order_purchase_timestamp       127595 non-null  datetime64[us]
 4   order_approved_at              127579 non-null  datetime64[us]
 5   order_delivered_timestamp      87427 non-null   datetime64[us]
 6   order_estimated_delivery_date  89316 non-null   datetime64[us]
dtypes: datetime64[us](4), str(3)
memory usage: 6.8 MB
None

Contagem final de nulos:
order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                   16
order_delivered_timestamp        40168
order_estimated_delivery_date    38279
dtype: int64

### 2. Limpeza Pagamentos

In [29]:
# Carregando dataset
df_Payments = pd.read_csv('df_Payments.csv')
df_Payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15
...,...,...,...,...,...
127590,QKBW3XKevmfn,1,credit_card,1,209.51
127591,Tjiw9bj8HtLr,1,credit_card,2,323.31
127592,mCPofb7A1aTq,1,wallet,1,170.71
127593,scVuqN10zbgb,1,credit_card,10,100.65
127594,oLKXX8tqU6eQ,1,credit_card,4,984.20

In [30]:
# Verificando tipos
df_Payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [31]:
# Quantos dados NAN existem
df_Payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [32]:
# Mostrar se existe espaços em branco
df_Payments['payment_type'].str.contains(' ').sum()

np.int64(0)

### 4. Limpeza Produtos

In [33]:
# Carregando dataset
df_Products = pd.read_csv('df_Products.csv')
df_Products.head(10)

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0
5,TpFZIk33uyGn,toys,2800.0,16.0,31.0,39.0
6,Y0T4Ca4BXK8U,bed_bath_table,3975.0,46.0,12.0,43.0
7,IUykT5z5LcPW,toys,250.0,45.0,15.0,35.0
8,0UHKKyYmxWfq,toys,1200.0,30.0,23.0,30.0
9,MJ82dNJNiV7U,toys,1500.0,30.0,5.0,20.0

In [34]:
# Quantos dados NAN existem
df_Products.isnull().sum()

product_id               0
product_category_name    0
product_weight_g         2
product_length_cm        2
product_height_cm        2
product_width_cm         2
dtype: int64

In [35]:
# Verificando tipos
df_Products.dtypes

product_id                   str
product_category_name        str
product_weight_g         float64
product_length_cm        float64
product_height_cm        float64
product_width_cm         float64
dtype: object

In [36]:
# Verificando se existe espaços vazios
df_Products['product_category_name'].str.contains(' ').sum()

np.int64(170)

In [37]:
# Resolvendo os valores nulos
df_Products['product_category_name'] = df_Products['product_category_name'].fillna("Não informado")

In [38]:
# Investigando quais dados da coluna estão NAN
df_Products[df_Products["product_weight_g"].isnull()]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1803,zX9HL81jfvr2,toys,NaN,NaN,NaN,NaN
8274,VqyFCmRtRdfR,toys,NaN,NaN,NaN,NaN

In [39]:
# Total de linhas duplicadas
total_duplicados_Products = df_Products.duplicated().sum()
total_duplicados_Products

np.int64(0)

In [40]:
# 1. Remove linhas completamente idênticas
df_limpo = df_Products.drop_duplicates()

# 2. Compara o total de linhas com o total de IDs únicos
total_linhas = len(df_limpo)
ids_unicos = df_limpo['product_id'].nunique()

print(f"Total de linhas (sem duplicadas exatas): {total_linhas}")
print(f"Total de product_id únicos: {ids_unicos}")

if total_linhas == ids_unicos:
    print("Sucesso: Cada product_id é único na tabela!")
else:
    print(f"Atenção: Existem {total_linhas - ids_unicos} IDs repetidos com dados diferentes.")

    # Diagnosticado que os dados nulos eram dados duplicados com o mesmo numero de ID também.

Total de linhas (sem duplicadas exatas): 32951
Total de product_id únicos: 32951
Sucesso: Cada product_id é único na tabela!

In [41]:
# Após a validação, removendo duplicidades do dataset original
df_Products = df_Products.drop_duplicates()

In [42]:
#  CORRETO: Atribuindo de volta à variável
df_Products = df_Products.drop_duplicates(subset=['product_id'])
df_Products.to_sql('products', engine, if_exists='replace', index=False) # Envia o dataset limpo!

NameError: name 'engine' is not defined

In [43]:
# 2. SALVAR AS MUDANÇAS E SOBRESCREVER OS CSVs NO DISCO:
# O parâmetro index=False evita criar uma coluna extra de numeração no CSV
df_Customers.to_csv('df_Customers.csv', index=False)
df_OrderItems.to_csv('df_OrderItems.csv', index=False)
df_Orders.to_csv('df_Orders.csv', index=False)
df_Payments.to_csv('df_Payments.csv', index=False)
df_Products.to_csv('df_Products.csv', index=False)

print("Todos os arquivos CSV foram sobrescritos e salvos com sucesso!")

Todos os arquivos CSV foram sobrescritos e salvos com sucesso!